apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: get-method
route:
  methods:
    - get
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-mocking-m0
plugin: mocking
config:
  api_specification_filename: orders.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pizza-order-api-0
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: add-mocking-m0
    konghq.com/override: get-method
spec:
  rules:
    - host: mockbin.org
      http:
        paths:
          - backend:
              service:
                name: pizza-order-api-service-0
                port:
                  number: 80
            path: /request/v1/order/.*
            pathType: ImplementationSpecific

